version: '3.8'

networks:
  vector:
  vector1:
  
volumes:
  database_node:
    driver_opts:
      type: tmpfs
      device: tmpfs
  database_router0:
    driver_opts:
      type: tmpfs
      device: tmpfs
  database_node1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  database_router1:
    driver_opts:
      type: tmpfs
      device: tmpfs  

services:

  node:
    networks:
      - 'vector'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'
    image: 'connextproject/vector_node:0.2.5-beta.16'
    restart: always
    ports:
      - '8002:8000'  
    environment:
      VECTOR_CONFIG: '{
  "adminToken": "cxt1234",
  "chainAddresses": {},
  "chainProviders": {
    "4": "https://rinkeby.infura.io/v3/af2f28bdb95d40edb06226a46106f5f9"
  },
  "logLevel": "info",
  "messagingUrl": "https://messaging.connext.network",
  "production": false,
  "allowedSwaps": [
    {
      "fromChainId": 4,
      "toChainId": 4,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    }
  ],
  "rebalanceProfiles": [
    {
      "chainId": 4,
      "assetId": "0x0000000000000000000000000000000000000000",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    }
  ]
}'
      VECTOR_PROD: 'true'
      VECTOR_MNEMONIC: 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database-node'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'



  router:
    networks:
      - 'vector'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'
    image: 'connextproject/vector_router:0.2.5-beta.16'
    environment:
      VECTOR_CONFIG: '{
  "adminToken": "cxt1234",
  "chainAddresses": {},
  "chainProviders": {
    "4": "https://rinkeby.infura.io/v3/af2f28bdb95d40edb06226a46106f5f9"
  },
  "logLevel": "info",
  "messagingUrl": "https://messaging.connext.network",
  "production": false,
  "allowedSwaps": [
    {
      "fromChainId": 4,
      "toChainId": 4,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    }
  ],
  "rebalanceProfiles": [
    {
      "chainId": 4,
      "assetId": "0x0000000000000000000000000000000000000000",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    }
  ]
}'
      VECTOR_PROD: 'true'
      VECTOR_NODE_URL: 'http://node:8000'
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database-router0'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
      VECTOR_MNEMONIC: 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
      
  database-node:
    volumes:
      - database_node:/var/lib/postgresql/data
    networks:
      - 'vector'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'
    image: 'vector_database:latest'

    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRES_DB: 'vector'
      POSTGRES_PASSWORD: 'vector'
      POSTGRES_PASSWORD_FILE: ''
      POSTGRES_USER: 'vector'
      VECTOR_ADMIN_TOKEN: 'cxt1234'
      VECTOR_PROD: 'true'
      
  database-router0:
    volumes:
      - database_router0:/var/lib/postgresql/data
    networks:
      - 'vector'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
    image: 'vector_database:latest'

    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRES_DB: 'vector'
      POSTGRES_PASSWORD: 'vector'
      POSTGRES_PASSWORD_FILE: ''
      POSTGRES_USER: 'vector'
      VECTOR_ADMIN_TOKEN: 'cxt1234'
      VECTOR_PROD: 'true'

  node1:
    networks:
      - 'vector1'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'
    image: 'connextproject/vector_node:0.2.5-beta.16'
    restart: always
    ports:
      - '8014:8000'  
    environment:
      VECTOR_CONFIG: '{
  "adminToken": "cxt1234",
  "chainAddresses": {},
  "chainProviders": {
    "4": "https://rinkeby.infura.io/v3/af2f28bdb95d40edb06226a46106f5f9"
  },
  "logLevel": "info",
  "messagingUrl": "https://messaging.connext.network",
  "production": false,
  "allowedSwaps": [
    {
      "fromChainId": 4,
      "toChainId": 4,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    }
  ],
  "rebalanceProfiles": [
    {
      "chainId": 4,
      "assetId": "0x0000000000000000000000000000000000000000",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    }
  ]
}'
      VECTOR_PROD: 'true'
      VECTOR_MNEMONIC: 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
      

  router1:
    networks:
      - 'vector1'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'
    image: 'connextproject/vector_router:0.2.5-beta.16'
    environment:
      VECTOR_CONFIG: '{
  "adminToken": "cxt1234",
  "chainAddresses": {},
  "chainProviders": {
    "4": "https://rinkeby.infura.io/v3/af2f28bdb95d40edb06226a46106f5f9"
  },
  "logLevel": "info",
  "messagingUrl": "https://messaging.connext.network",
  "production": false,
  "allowedSwaps": [
    {
      "fromChainId": 4,
      "toChainId": 4,
      "fromAssetId": "0x0000000000000000000000000000000000000000",
      "toAssetId": "0x0000000000000000000000000000000000000000",
      "priceType": "hardcoded",
      "hardcodedRate": "1"
    }
  ],
  "rebalanceProfiles": [
    {
      "chainId": 4,
      "assetId": "0x0000000000000000000000000000000000000000",
      "reclaimThreshold": "1",
      "target": "0",
      "collateralizeThreshold": "0"
    }
  ]
}'
      VECTOR_PROD: 'true'
      VECTOR_NODE_URL: 'http://node1:8000'
      VECTOR_PG_DATABASE: 'vector'
      VECTOR_PG_HOST: 'database-router1'
      VECTOR_PG_PASSWORD: 'vector'
      VECTOR_PG_PORT: '5432'
      VECTOR_PG_USERNAME: 'vector'
      VECTOR_MNEMONIC: 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat'

  database-node1:
    volumes:
      - database_node1:/var/lib/postgresql/data
    networks:
      - 'vector1'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'

    image: 'vector_database:latest'
 
    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRES_DB: 'vector'
      POSTGRES_PASSWORD: 'vector'
      POSTGRES_PASSWORD_FILE: ''
      POSTGRES_USER: 'vector'
      VECTOR_ADMIN_TOKEN: 'cxt1234'
      VECTOR_PROD: 'true'          
#
  database-router1:
    volumes:
      - database_router1:/var/lib/postgresql/data
    networks:
      - 'vector1'
    logging:
      driver: 'json-file'
      options:
          max-size: '10m'
    image: 'vector_database:latest'

    environment:
      AWS_ACCESS_KEY_ID: ''
      AWS_SECRET_ACCESS_KEY: ''
      POSTGRES_DB: 'vector'
      POSTGRES_PASSWORD: 'vector'
      POSTGRES_PASSWORD_FILE: ''
      POSTGRES_USER: 'vector'
      VECTOR_ADMIN_TOKEN: 'cxt1234'
      VECTOR_PROD: 'true'
